# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://SNXJ.github.io
date_format: "ordinal"
title: 骚年！小杰！
subtitle: "书写改变人生"
description: "骚年的个人博客"
keywords: 骚年, SNXJ, 码农
favicon: /favicon.ico
timezone: Asia/beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: SNXJ
organization: Zhnagfujr
organization_url: http://www.zhangfujr.com/
location: 上海
email: 927990956@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: SNXJ/SNXJ.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: SNXJ

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: SNXJ
disqus_username: SNXJ
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
   analytics_id: UA-88357790-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Kotlin，Flutter,TS,C++, Python]
skill_mobile_app_keywords: [Android,Flutter, Uni,HM]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
