title: SNXJ
description: My Personal Blog
author: SNXJ
logo: /SNXJ.github.io/static/img/avatar.png
github: https://github.com/SNXJ
about: 开发者不自由

baseurl: "https://github.com/SNXJ"
url: "https://github.com/SNXJ"

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000sss


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
